#!/usr/bin/env python3
"""Exact/high-precision certificate for the moving rank-one midpoint theorem.

The symbolic proof is in moving_rank1_theorem.md.  This script checks one
six-coordinate rational fixture, reconstructs all 64 exact DPP atoms by the
signed event-determinant formula, verifies the rank-two mass-transfer bridge,
checks the independent bit-flip identity exactly, and evaluates the explicit
Fannes--Audenaert margin bound with 100 decimal digits.
"""
from __future__ import annotations

from itertools import combinations
import mpmath as mp
import sympy as sp

Q = sp.Rational
N = 6
EPS = Q(1, 1000)


def subsets(n: int):
    for mask in range(1 << n):
        yield tuple(i for i in range(n) if mask & (1 << i))


def event_matrix(K: sp.Matrix, S: tuple[int, ...]) -> sp.Matrix:
    M = K.copy()
    inside = set(S)
    for i in range(K.rows):
        if i not in inside:
            M[i, i] -= 1
    return M


def event_prob(K: sp.Matrix, S: tuple[int, ...]) -> sp.Rational:
    return sp.factor((-1) ** (K.rows - len(S)) * event_matrix(K, S).det())


def law(K: sp.Matrix) -> dict[tuple[int, ...], sp.Rational]:
    out = {S: event_prob(K, S) for S in subsets(K.rows)}
    assert all(p >= 0 for p in out.values())
    assert sum(out.values(), Q(0)) == 1
    return out


def mpq(x: sp.Rational) -> mp.mpf:
    return mp.mpf(int(x.p)) / int(x.q)


def entropy(p: dict[tuple[int, ...], sp.Rational]) -> mp.mpf:
    total = mp.mpf("0")
    for x in p.values():
        if x:
            y = mpq(x)
            total -= y * mp.log(y)
    return total


def h2(x: mp.mpf) -> mp.mpf:
    if x == 0 or x == 1:
        return mp.mpf("0")
    return -x * mp.log(x) - (1 - x) * mp.log(1 - x)


def bitflip_law(
    p: dict[tuple[int, ...], sp.Rational], eps: sp.Rational
) -> dict[tuple[int, ...], sp.Rational]:
    masks = range(1 << N)
    by_mask = {
        sum(1 << i for i in S): mass
        for S, mass in p.items()
    }
    out: dict[tuple[int, ...], sp.Rational] = {}
    for target in masks:
        total = Q(0)
        for source in masks:
            d = (source ^ target).bit_count()
            total += by_mask[source] * eps**d * (1 - eps) ** (N - d)
        S = tuple(i for i in range(N) if target & (1 << i))
        out[S] = sp.factor(total)
    assert sum(out.values(), Q(0)) == 1
    assert all(x > 0 for x in out.values())
    return out


def fmt(x: mp.mpf, digits: int = 70) -> str:
    return mp.nstr(x, digits)


# A rational orthogonal frame generated by one Householder reflection.
h = sp.Matrix([1, 2, 3, 4, 5, 6])
R = sp.eye(N) - Q(2, 91) * h * h.T
u = R[:, 0]
z = R[:, 1]
v = (3 * u + 4 * z) / 5
assert (u.T * u)[0] == 1
assert (v.T * v)[0] == 1
assert (u.T * v)[0] == Q(3, 5)

a = Q(7, 10)
b = Q(4, 5)
K_minus = a * u * u.T
K_plus = b * v * v.T
K_mid = (K_minus + K_plus) / 2
assert K_mid == (K_minus + K_plus) / 2

p_minus = law(K_minus)
p_plus = law(K_plus)
p_mid = law(K_mid)
q_mix = {S: (p_minus[S] + p_plus[S]) / 2 for S in p_mid}

# Rank-one endpoints have only empty and singleton atoms.
assert all(p_minus[S] == 0 for S in p_minus if len(S) >= 2)
assert all(p_plus[S] == 0 for S in p_plus if len(S) >= 2)
assert p_minus[()] == 1 - a
assert p_plus[()] == 1 - b
for i in range(N):
    assert p_minus[(i,)] == a * u[i] ** 2
    assert p_plus[(i,)] == b * v[i] ** 2

# The midpoint has rank two.  Its pair mass m equals the product of its two
# nonzero eigenvalues and can be obtained without radicals from e_2(K).
s = sp.trace(K_mid)
m = sp.factor((s**2 - sp.trace(K_mid * K_mid)) / 2)
assert s == (a + b) / 2
assert m > 0
assert all(p_mid[S] == 0 for S in p_mid if len(S) >= 3)
assert sum(p_mid[S] for S in p_mid if len(S) == 2) == m

# Exact mass-transfer bridge q=p_0 -> p_K=p_m.  Define b_ij=p_ij/m and
# c_i=sum_j b_ij.  Then p_mid(empty)=q(empty)+m and
# p_mid(i)=q(i)-m c_i for every coordinate.
bij: dict[tuple[int, int], sp.Rational] = {}
for i, j in combinations(range(N), 2):
    bij[(i, j)] = sp.factor(p_mid[(i, j)] / m)
assert sum(bij.values(), Q(0)) == 1
ci = []
for i in range(N):
    ci.append(sum(value for (r, t), value in bij.items() if i in (r, t)))
assert p_mid[()] == q_mix[()] + m
for i in range(N):
    assert p_mid[(i,)] == q_mix[(i,)] - m * ci[i]

# At three exact interior values of r, every active derivative logarithm has
# ratio >1.  The markdown proof establishes this for the full open interval.
for r in (m / 4, m / 2, 3 * m / 4):
    p0 = 1 - s + r
    for (i, j), weight in bij.items():
        if weight:
            pi = q_mix[(i,)] - r * ci[i]
            pj = q_mix[(j,)] - r * ci[j]
            assert pi * pj > p0 * r * weight

# Strict interior common bit-flip lift and exact channel identity.
I = sp.eye(N)
K_minus_e = EPS * I + (1 - 2 * EPS) * K_minus
K_plus_e = EPS * I + (1 - 2 * EPS) * K_plus
K_mid_e = EPS * I + (1 - 2 * EPS) * K_mid
assert K_mid_e == (K_minus_e + K_plus_e) / 2

p_minus_e = law(K_minus_e)
p_plus_e = law(K_plus_e)
p_mid_e = law(K_mid_e)
assert p_minus_e == bitflip_law(p_minus, EPS)
assert p_plus_e == bitflip_law(p_plus, EPS)
assert p_mid_e == bitflip_law(p_mid, EPS)

# Exact spectral legality follows directly from the eigenvalue map; also check
# positive definiteness through all leading principal minors for the fixture.
for K in (K_minus_e, K_plus_e, K_mid_e):
    for M in (K, I - K):
        assert all(M[:k, :k].det() > 0 for k in range(1, N + 1))

mp.mp.dps = 110
Hm = entropy(p_minus)
Hp = entropy(p_plus)
H0 = entropy(p_mid)
G = H0 - (Hm + Hp) / 2
assert G > 0

delta = 1 - mpq((1 - EPS) ** N)
omega = h2(delta) + delta * mp.log(2**N - 1)
certified = G - 2 * omega
assert delta < 1 - mp.mpf(1) / 2**N
assert certified > 0

Hm_e = entropy(p_minus_e)
Hp_e = entropy(p_plus_e)
H0_e = entropy(p_mid_e)
G_e = H0_e - (Hm_e + Hp_e) / 2
assert G_e > certified > 0

print("agent24 moving-rank-one exact fixture: PASS")
print("dimension =", N)
print("u =", [str(x) for x in u])
print("v =", [str(x) for x in v])
print("a =", a, "; b =", b, "; <u,v> =", (u.T * v)[0])
print("endpoint nonzero atom counts =", sum(1 for x in p_minus.values() if x > 0), sum(1 for x in p_plus.values() if x > 0))
print("midpoint nonzero atom count =", sum(1 for x in p_mid.values() if x > 0))
print("smallest nonzero midpoint atom =", min(x for x in p_mid.values() if x > 0))
print("rank-two transfer mass m =", m)
print("H(K_minus) =", fmt(Hm))
print("H(K_plus)  =", fmt(Hp))
print("H(K_mid)   =", fmt(H0))
print("boundary Jensen margin =", fmt(G))
print("epsilon =", EPS)
print("bit-flip TV coupling bound delta =", fmt(delta))
print("Fannes-Audenaert omega_6(epsilon) =", fmt(omega))
print("certified strict-lift margin lower bound G-2 omega =", fmt(certified))
print("actual strict-lift Jensen margin =", fmt(G_e))
print("strict-lift minimum atom minus =", min(p_minus_e.values()))
print("strict-lift minimum atom plus =", min(p_plus_e.values()))
print("strict-lift minimum atom midpoint =", min(p_mid_e.values()))
